name: Build and publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
      - name: Latest XCode
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
        
      - name: Prepare database
        run: |
          curl --output google_play_devices.csv https://storage.googleapis.com/play_public/supported_devices.csv

          XCODE_PATH=$(xcode-select -p)
          IPHONE_TRAITS_PATH="$XCODE_PATH/Platforms/iPhoneOS.platform/usr/standalone/device_traits.db"

          dotnet run --project Generator -- -GooglePlayDevices google_play_devices.csv -AppleDevices "$IPHONE_TRAITS_PATH"

          DATE=$(date +'%Y%m%d')
          VERSION="0.0.${DATE}-packagingtest"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if database is updated
        id: check_db_updated
        run: |
          if cmp -s Database.dat Lookup/Resources/Database.dat; then
            echo "Database is up to date."
            echo "db_updated=false" >> $GITHUB_OUTPUT
          else
            mv Database.dat Lookup/Resources/Database.dat
            echo "db_updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Build package
        if: steps.check_db_updated.outputs.check_db_updated == true
        run: |
          dotnet build Lookup --configuration Release
          dotnet pack Lookup --configuration Release --no-build -o ./artifacts -p:PackageVersion=${{ env.VERSION }}

      - name: NuGet login
        if: steps.check_db_updated.outputs.check_db_updated == true
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      # Push the package
      - name: NuGet push
        if: steps.check_db_updated.outputs.check_db_updated == true
        run: |
          dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
          dotnet nuget push artifacts/*.snupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
